# Data Preprocessing

In [5]:
pip install pandas numpy

Collecting pandas
  Downloading pandas-2.2.3-cp311-cp311-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Downloading numpy-2.2.1-cp311-cp311-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp pavilion gaming\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\hp pavilion gaming\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.2.3-cp311-cp311-win_amd64.whl (11.6 MB)
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
    --------------------------------------- 0.3/11.6 MB ? eta -:--:--
   --- ------------------------------------ 1.0/11.6 MB 2.8 MB/s eta 0:00:04
   ----- ---------------------------------- 1.6/11.6 MB 2.7 MB/s eta 0:00:04
   ------- -------------------------------- 2.1/11.6 MB 2.6 MB/s eta 0:00:04
   --------- ------------------------------ 2.6/11.6 MB 2.6 MB/s eta 0:00:04
   --------- ------------------------------ 2.9/11.6 MB 2.5 MB/s eta 0:00:04
   ------------ --------------------------- 3.7/11.6 MB 2.5 MB/s eta 0:00:04
   -------------- ------------------------- 4.2/11.6 MB 2.5 MB/s eta 0:00:03
   ---------------- ----------------------- 4.7/11.6 MB 2.5 MB/s eta 0:00:03
   ------------------ --------------------- 5.2/11.6 MB 2.5 MB/s eta 0:00:03
   ------------------- -------------------- 5.8/11.6 MB 2.5 MB/s eta 0:00:03
   --------------------- ------------------ 6.3/11.6 MB 2.5 MB/s eta 0:00:03
   ----------------------- ---------------- 6.8/11.6 MB 2.5 MB/s eta 0:00:02
   ------------------------- -------------- 7.3/11.6 MB 2.5 MB/s eta 0:00:02
   --------------------------- ------------ 7.9/11.6 MB 2.5 MB/s eta 0:00:02
   ---------------------------- ----------- 8.4/11.6 MB 2.5 MB/s eta 0:00:02
   ----------------------------- ---------- 8.7/11.6 MB 2.5 MB/s eta 0:00:02
   -------------------------------- ------- 9.4/11.6 MB 2.5 MB/s eta 0:00:01
   --------------------------------- ------ 9.7/11.6 MB 2.5 MB/s eta 0:00:01
   ----------------------------------- ---- 10.2/11.6 MB 2.4 MB/s eta 0:00:01
   ------------------------------------ --- 10.5/11.6 MB 2.4 MB/s eta 0:00:01
   ------------------------------------- -- 10.7/11.6 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------  11.5/11.6 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------- 11.6/11.6 MB 2.3 MB/s eta 0:00:00
Downloading numpy-2.2.1-cp311-cp311-win_amd64.whl (12.9 MB)
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.9 MB 2.8 MB/s eta 0:00:05
   --- ------------------------------------ 1.0/12.9 MB 2.5 MB/s eta 0:00:05
   ---- ----------------------------------- 1.6/12.9 MB 2.5 MB/s eta 0:00:05
   ------ --------------------------------- 2.1/12.9 MB 2.4 MB/s eta 0:00:05
   -------- ------------------------------- 2.6/12.9 MB 2.5 MB/s eta 0:00:05
   --------- ------------------------------ 3.1/12.9 MB 2.5 MB/s eta 0:00:04
   --------- ------------------------------ 3.1/12.9 MB 2.5 MB/s eta 0:00:04
   ---------- ----------------------------- 3.4/12.9 MB 2.2 MB/s eta 0:00:05
   ------------ --------------------------- 3.9/12.9 MB 2.1 MB/s eta 0:00:05
   ------------- -------------------------- 4.5/12.9 MB 2.1 MB/s eta 0:00:05
   --------------- ------------------------ 5.0/12.9 MB 2.1 MB/s eta 0:00:04
   ----------------- ---------------------- 5.5/12.9 MB 2.2 MB/s eta 0:00:04
   ------------------ --------------------- 6.0/12.9 MB 2.2 MB/s eta 0:00:04
   -------------------- ------------------- 6.6/12.9 MB 2.2 MB/s eta 0:00:03
   --------------------- ------------------ 7.1/12.9 MB 2.2 MB/s eta 0:00:03
   ----------------------- ---------------- 7.6/12.9 MB 2.2 MB/s eta 0:00:03
   ------------------------ --------------- 7.9/12.9 MB 2.2 MB/s eta 0:00:03
   -------------------------- ------------- 8.7/12.9 MB 2.3 MB/s eta 0:00:02
   ---------------------------- ----------- 9.2/12.9 MB 2.3 MB/s eta 0:00:02
   ----------------------------- ---------- 9.4/12.9 MB 2.2 MB/s eta 0:00:02
   ------------------------------ --------- 10.0/12.9 MB 2.2 MB/s eta 0:00:02
   -------------------------------- ------- 10.5/12.9 MB 2.2 MB/s eta 0:00:02
   ---------------------------------- ----- 11.0/12.9 MB 2.3 MB/s eta 0:00:01
   ----------------------------------- ---- 11.5/12.9 MB 2.3 MB/s eta 0:00:01
   ------------------------------------- -- 12.1/12.9 MB 2.3 MB/s eta 0:00:01
   -------------------------------------- - 12.6/12.9 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------- 12.9/12.9 MB 2.3 MB/s eta 0:00:00
Using cached pytz-2024.2-py2.py3-none-any.whl (508 kB)
Using cached tzdata-2024.2-py2.py3-none-any.whl (346 kB)
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-2.2.1 pandas-2.2.3 pytz-2024.2 tzdata-2024.2
Note: you may need to restart the kernel to use updated packages.

In [3]:
# Import Packages
import pandas as pd
import numpy as np

In [9]:
import os

print(os.getcwd())  # This prints where your script thinks it is executing from.

c:\Users\HP Pavilion Gaming\Documents\Machine_Learning_Projects\Telco-Customer-Churn\02_data cleaning

In [12]:
df = pd.read_csv("telco-cust-churn-dataset-for-cleaning.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
 21  Unnamed: 21       7043 non-null   float64
dtypes: float64(2), int64(2), object(18)
memory usage: 1.2+ MB

In [13]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Unnamed: 21
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,29.85
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,No,One year,No,Mailed check,56.95,1889.5,No,1936.30
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,107.70
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,1903.50
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,141.40

In [20]:
# Determine categorical variables for One-hot encoding
col_list = list(df.columns)
for col in col_list:
    col_unique = df[col].nunique()
    print(f"Column {col} has {col_unique} unique values\n")

Column customerID has 7043 unique values

Column gender has 2 unique values

Column SeniorCitizen has 2 unique values

Column Partner has 2 unique values

Column Dependents has 2 unique values

Column tenure has 73 unique values

Column PhoneService has 2 unique values

Column MultipleLines has 3 unique values

Column InternetService has 3 unique values

Column OnlineSecurity has 3 unique values

Column OnlineBackup has 3 unique values

Column DeviceProtection has 3 unique values

Column TechSupport has 3 unique values

Column StreamingTV has 3 unique values

Column StreamingMovies has 3 unique values

Column Contract has 3 unique values

Column PaperlessBilling has 2 unique values

Column PaymentMethod has 4 unique values

Column MonthlyCharges has 1585 unique values

Column TotalCharges has 6531 unique values

Column Churn has 2 unique values

Column Unnamed: 21 has 5980 unique values

In [21]:
# Empty dummy columns list
encode_list = []

# Fill the dummy list with categorical variables 
# Assumption if there are no more than 3 unique categories in the column
for col in col_list:
    if df[col].nunique() <= 3:
        encode_list.append(col)

In [22]:
encode_list

['gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'Churn']

## One-Hot Encoding Categorical Variables

* For modeling purposes, the sklearn.preprocessing package will be used
* OneHotEncoder will be used for categorical variables, as well as the 'Churn' variable

In [32]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [37]:
## Encoder
# enc = OneHotEncoder(sparse=False,drop='first')
label_encoder = LabelEncoder()

# Create a DataFrame with the encoded columns
df_proc = df.copy()
for col in encode_list:
    df_proc[col] = label_encoder.fit_transform(df[col])

In [41]:
# Comparison
df_proc = df_proc.drop('Unnamed: 21', axis=1)
df_proc.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,0,0,1,0,1,0,1,0,0,...,0,0,0,0,0,1,Electronic check,29.85,29.85,0
1,5575-GNVDE,1,0,0,0,34,1,0,0,2,...,2,0,0,0,1,0,Mailed check,56.95,1889.5,0
2,3668-QPYBK,1,0,0,0,2,1,0,0,2,...,0,0,0,0,0,1,Mailed check,53.85,108.15,1
3,7795-CFOCW,1,0,0,0,45,0,1,0,2,...,2,2,0,0,1,0,Bank transfer (automatic),42.30,1840.75,0
4,9237-HQITU,0,0,0,0,2,1,0,1,0,...,0,0,0,0,0,1,Electronic check,70.70,151.65,1

In [42]:
df_proc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   int32
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   int32
 4   Dependents        7043 non-null   int32
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   int32
 7   MultipleLines     7043 non-null   int32
 8   InternetService   7043 non-null   int32
 9   OnlineSecurity    7043 non-null   int32
 10  OnlineBackup      7043 non-null   int32
 11  DeviceProtection  7043 non-null   int32
 12  TechSupport       7043 non-null   int32
 13  StreamingTV       7043 non-null   int32
 14  StreamingMovies   7043 non-null   int32
 15  Contract          7043 non-null   int32
 16  PaperlessBilling  7043 non-null   int32
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   int32
dtypes: float64(1), int32(15), int64(2), object(3)
memory usage: 742.9+ KB

## Create csv from dataframe in New Folder

In [45]:
# source_dir = os.getcwd()
# destination_dir = os.path.dirname(source_dir + '\\..\\..\\03_EDA-to-Modeling')

# # Step 3: Create intermediate directories if they don’t exist
# intermediate_dirs = [
#     *filter(lambda x: len(x.split('\\')) > len(destination_dir.split('\\')), 
#            map(lambda x: os.path.normcase(x), os.walk('.')))
# ]

# for dir_name in intermediate_dirs[::-1]:
#     os.makedirs(dir_name, exist_ok=True)

# # Step 4: Construct final destination path within ‘03_EDA-to-Modeling’
# final_destination_path = os.path.join(destination_dir, 'churn_data.csv')

# # Step 5: Save DataFrame as CSV file at final destination path
# df.to_csv(final_destination_path, index=False)

# print(f"DataFrame saved to {final_destination_path}")